
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSong_ce2de38ea9
ROOST_METHOD_SIG_HASH=addSong_144dbf05b2


Scenario 1: Valid song is inserted successfully and returns OK with JSON data

Details:
  TestName: addSong_withValidSong_returnsOkAndSetsJsonData
  Description: Verifies that when all required fields (song name, album, artist full name) are non-null, SongDalImpl.addSong invokes MongoTemplate.insert with the "songs" collection, receives a non-null Song, and returns a DbQueryStatus with operation "POST", result QUERY_OK, and a data payload equal to the inserted Song’s JSON representation.

Execution:
  Arrange:
    - Create a mock MongoTemplate and inject it into a SongDalImpl instance (via constructor or reflection).
    - Create a mock Song for input (songToAdd) where getSongName, getSongAlbum, and getSongArtistFullName each return non-null values.
    - Stub db.insert(songToAdd, "songs") to return a non-null mock Song (inserted).
    - Stub inserted.getJsonRepresentation() to return a known JSON string (e.g., "{\"id\":\"123\"}").

  Act:
    - Call addSong(songToAdd).

  Assert:
    - Verify db.insert was called exactly once with songToAdd and "songs".
    - Use JUnit assertions to check that:
      - The returned DbQueryStatus has operation "POST".
      - The execution result is DbQueryExecResult.QUERY_OK.
      - The data payload equals the JSON from inserted.getJsonRepresentation().

Validation:
  Confirms the happy path where a valid input triggers a DB insert and a successful status with the response payload set from the inserted entity’s JSON. Ensures correct wiring to the "songs" collection and the correct success signal.

*/

// ********RoostGPT********

package com.csc301.songmicroservice;

import com.mongodb.client.result.DeleteResult;
import org.bson.types.ObjectId;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.mockito.ArgumentMatchers;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.data.mongodb.core.MongoTemplate;
import java.util.HashMap;
import java.util.Map;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

@RunWith(MockitoJUnitRunner.class)
public class SongDalImplAddSongTest {

	@Mock
	private MongoTemplate mongoTemplate;

	@Mock
	private Song songToAdd;

	@Mock
	private Song insertedSong;

	private SongDalImpl sut;

	@Before
	public void setUp() {
		// Use constructor injection as per provided information
		sut = new SongDalImpl(mongoTemplate);
	}

	@Test
    @Category(Categories.valid.class)
    public void addSong_withValidSong_returnsOkAndSetsJsonData() {
        when(songToAdd.getSongName()).thenReturn("song");
        when(songToAdd.getSongAlbum()).thenReturn("album");
        when(songToAdd.getSongArtistFullName()).thenReturn("artist");
        Map<String, String> jsonMap = new HashMap<String, String>();
        jsonMap.put("id", "123");
        when(mongoTemplate.insert((Song) ArgumentMatchers.eq(songToAdd), (String) ArgumentMatchers.eq("songs"))).thenReturn(insertedSong);
        when(insertedSong.getJsonRepresentation()).thenReturn(jsonMap);
        DbQueryStatus status = sut.addSong(songToAdd);
        verify(mongoTemplate, times(1)).insert((Song) ArgumentMatchers.eq(songToAdd), (String) ArgumentMatchers.eq("songs"));
        assertEquals((String) "POST", (String) status.getMessage());
        assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
        assertSame((Object) jsonMap, (Object) status.getData());
    }

	@Test
    @Category(Categories.invalid.class)
    public void addSong_withNullSongName_returnsErrAndDoesNotInsert() {
        when(songToAdd.getSongName()).thenReturn(null);
        when(songToAdd.getSongAlbum()).thenReturn("album");
        when(songToAdd.getSongArtistFullName()).thenReturn("artist");
        DbQueryStatus status = sut.addSong(songToAdd);
        verify(mongoTemplate, never()).insert(any(Song.class), (String) ArgumentMatchers.eq("songs"));
        assertEquals((String) "POST", (String) status.getMessage());
        assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
        assertNull((Object) status.getData());
    }

	@Test
    @Category(Categories.invalid.class)
    public void addSong_withNullAlbum_returnsErrAndDoesNotInsert() {
        when(songToAdd.getSongName()).thenReturn("song");
        when(songToAdd.getSongAlbum()).thenReturn(null);
        when(songToAdd.getSongArtistFullName()).thenReturn("artist");
        DbQueryStatus status = sut.addSong(songToAdd);
        verify(mongoTemplate, never()).insert(any(Song.class), (String) ArgumentMatchers.eq("songs"));
        assertEquals((String) "POST", (String) status.getMessage());
        assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
        assertNull((Object) status.getData());
    }

	@Test
    @Category(Categories.invalid.class)
    public void addSong_withNullArtist_returnsErrAndDoesNotInsert() {
        when(songToAdd.getSongName()).thenReturn("song");
        when(songToAdd.getSongAlbum()).thenReturn("album");
        when(songToAdd.getSongArtistFullName()).thenReturn(null);
        DbQueryStatus status = sut.addSong(songToAdd);
        verify(mongoTemplate, never()).insert(any(Song.class), (String) ArgumentMatchers.eq("songs"));
        assertEquals((String) "POST", (String) status.getMessage());
        assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
        assertNull((Object) status.getData());
    }

	@Test
    @Category(Categories.boundary.class)
    public void addSong_withValidSongButInsertReturnsNull_returnsErrAndNoData() {
        when(songToAdd.getSongName()).thenReturn("song");
        when(songToAdd.getSongAlbum()).thenReturn("album");
        when(songToAdd.getSongArtistFullName()).thenReturn("artist");
        when(mongoTemplate.insert((Song) ArgumentMatchers.eq(songToAdd), (String) ArgumentMatchers.eq("songs"))).thenReturn(null);
        DbQueryStatus status = sut.addSong(songToAdd);
        verify(mongoTemplate, times(1)).insert((Song) ArgumentMatchers.eq(songToAdd), (String) ArgumentMatchers.eq("songs"));
        assertEquals((String) "POST", (String) status.getMessage());
        assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
        assertNull((Object) status.getData());
    }

	@Test
    @Category(Categories.boundary.class)
    public void addSong_validSong_insertedJsonNull_returnsOkWithNullData() {
        when(songToAdd.getSongName()).thenReturn("song");
        when(songToAdd.getSongAlbum()).thenReturn("album");
        when(songToAdd.getSongArtistFullName()).thenReturn("artist");
        when(mongoTemplate.insert((Song) ArgumentMatchers.eq(songToAdd), (String) ArgumentMatchers.eq("songs"))).thenReturn(insertedSong);
        when(insertedSong.getJsonRepresentation()).thenReturn(null);
        DbQueryStatus status = sut.addSong(songToAdd);
        verify(mongoTemplate, times(1)).insert((Song) ArgumentMatchers.eq(songToAdd), (String) ArgumentMatchers.eq("songs"));
        assertEquals((String) "POST", (String) status.getMessage());
        assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
        assertNull((Object) status.getData());
    }

	@Test
	@Category(Categories.invalid.class)
	public void addSong_withNullSong_throwsNullPointerException() {
		try {
			sut.addSong(null); // TODO: Ensure calling addSong with null is acceptable in
								// your codebase if behavior changes
			fail("Expected NullPointerException to be thrown");
		}
		catch (NullPointerException expected) {
			assertNotNull((Object) expected);
		}
	}

}