
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=deleteSongById_b471125b2d
ROOST_METHOD_SIG_HASH=deleteSongById_7a428ef6e2

Scenario 1: DAL returns QUERY_OK and remote service responds with status "OK"

Details:
  TestName: deleteSongOkAndRemoteOkYieldsFinalOk
  Description: Verifies that when songDal.deleteSongById returns DbQueryExecResult.QUERY_OK and the subsequent OkHttp call returns a JSON body with {"status":"OK"}, the controller preserves the success result and produces a response map reflecting success.

Execution:
  Arrange: Set up a mock SongDal to return a DbQueryStatus with DbQueryExecResult.QUERY_OK, a non-null message, and optional data. Configure OkHttpClient to return a Response whose body contains a JSON payload with a "status" key set to "OK". Provide an HttpServletRequest whose URL can be resolved by Utils.getUrl(request).
  Act: Invoke deleteSongById with a valid songId and the mocked HttpServletRequest.
  Assert: Use JUnit assertions to verify the returned Map is not null, contains "path" that begins with "DELETE " followed by the URL from Utils.getUrl(request), contains "message" equal to the mocked DbQueryStatus message, and reflects a final success state consistent with DbQueryExecResult.QUERY_OK as applied by Utils.setResponseStatus.

Validation:
  Confirms the happy-path behavior: a successful DAL delete followed by a successful remote call remains successful. Ensures the controller sets the "path" correctly and does not downgrade the status when the remote system reports "OK".

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import org.json.JSONObject;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import okhttp3.Call;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Protocol;
import okhttp3.Request;
import okhttp3.Response;
import java.util.HashMap;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import okhttp3.FormBody;
import okhttp3.RequestBody;

@RunWith(MockitoJUnitRunner.class)
public class SongControllerDeleteSongByIdTest {

	@Mock
	private SongDal songDal;

	@Mock
	private OkHttpClient client;

	@Mock
	private Call mockCall;

	@Mock
	private HttpServletRequest mockRequest;

	@InjectMocks
	private SongController controller;

	@Test
	@Category(Categories.valid.class)
	public void testDeleteSongOkAndRemoteOkYieldsFinalOk() throws Exception {
		// Arrange
		final String songId = "123"; // TODO change if your test song id format differs
		final DbQueryStatus okStatus = new DbQueryStatus("Delete successful", DbQueryExecResult.QUERY_OK);
		when(songDal.deleteSongById(songId)).thenReturn(okStatus);
		// Prepare request URL for Utils.getUrl(request)
		when(mockRequest.getRequestURL()).thenReturn(new StringBuffer("http://localhost:8080/api/songs/" + songId)); // TODO
																														// change
																														// if
																														// endpoint
																														// mapping
																														// differs
		when(mockRequest.getQueryString()).thenReturn(null);
		// Mock OkHttp remote call returning {"status":"OK"}
		final Request dummyReq = new Request.Builder().url("http://localhost/notify").build();
		final JSONObject okPayload = new JSONObject().put("status", "OK");
		final Response okResponse = new Response.Builder().request(dummyReq)
			.protocol(Protocol.HTTP_1_1)
			.code(200)
			.message("OK")
			.body(okhttp3.ResponseBody.create(MediaType.parse("application/json"), okPayload.toString()))
			.build();
		when(client.newCall(any(Request.class))).thenReturn(mockCall);
		when(mockCall.execute()).thenReturn(okResponse);
		// Act
		Map<String, Object> result = controller.deleteSongById(songId, mockRequest);
		// Assert
		assertNotNull(result);
		String expectedPath = "DELETE " + Utils.getUrl(mockRequest);
		assertEquals(expectedPath, (String) result.get("path"));
		assertEquals(okStatus.getMessage(), (String) result.get("message"));
		Object statusObj = result.get("status");
		assertNotNull(statusObj);
		assertEquals("OK", statusObj.toString());
		verify(songDal, times(1)).deleteSongById(songId);
		verify(client, times(1)).newCall(any(Request.class));
		verify(mockCall, times(1)).execute();
	}

}