
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSong_ce2de38ea9
ROOST_METHOD_SIG_HASH=addSong_144dbf05b2


Scenario 1: Valid song is inserted successfully and returns OK with JSON data

Details:
  TestName: addSong_withValidSong_returnsOkAndSetsJsonData
  Description: Verifies that when all required fields (song name, album, artist full name) are non-null, SongDalImpl.addSong invokes MongoTemplate.insert with the "songs" collection, receives a non-null Song, and returns a DbQueryStatus with operation "POST", result QUERY_OK, and a data payload equal to the inserted Song’s JSON representation.

Execution:
  Arrange:
    - Create a mock MongoTemplate and inject it into a SongDalImpl instance (via constructor or reflection).
    - Create a mock Song for input (songToAdd) where getSongName, getSongAlbum, and getSongArtistFullName each return non-null values.
    - Stub db.insert(songToAdd, "songs") to return a non-null mock Song (inserted).
    - Stub inserted.getJsonRepresentation() to return a known JSON string (e.g., "{\"id\":\"123\"}").

  Act:
    - Call addSong(songToAdd).

  Assert:
    - Verify db.insert was called exactly once with songToAdd and "songs".
    - Use JUnit assertions to check that:
      - The returned DbQueryStatus has operation "POST".
      - The execution result is DbQueryExecResult.QUERY_OK.
      - The data payload equals the JSON from inserted.getJsonRepresentation().

Validation:
  Confirms the happy path where a valid input triggers a DB insert and a successful status with the response payload set from the inserted entity’s JSON. Ensures correct wiring to the "songs" collection and the correct success signal.

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import com.mongodb.client.result.DeleteResult;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Repository;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;

@ExtendWith(MockitoExtension.class)
public class SongDalImplAddSongTest {

	@Mock
	private MongoTemplate mongoTemplate;

	@InjectMocks
	private SongDalImpl songDalImpl;

	@Test
	@Tag("valid")
	public void addSong_withValidSong_returnsOkAndSetsJsonData() {
		// Arrange
		Song songToAdd = mock(Song.class);
		when(songToAdd.getSongName()).thenReturn("name");
		when(songToAdd.getSongAlbum()).thenReturn("album");
		when(songToAdd.getSongArtistFullName()).thenReturn("artist");
		Song inserted = mock(Song.class);
		Map<String, String> json = Collections.emptyMap();
		when(inserted.getJsonRepresentation()).thenReturn(json);
		when(mongoTemplate.insert(songToAdd, "songs")).thenReturn(inserted);
		// Act
		DbQueryStatus status = songDalImpl.addSong(songToAdd);
		// Assert
		verify(mongoTemplate, times(1)).insert(songToAdd, "songs");
		assertEquals((String) "POST", (String) status.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
		assertEquals((Object) json, (Object) status.getData());
	}

	@Test
	@Tag("invalid")
	public void addSong_withNullName_doesNotInsertAndReturnsError() {
		// Arrange
		Song songToAdd = mock(Song.class);
		when(songToAdd.getSongName()).thenReturn(null);
		when(songToAdd.getSongAlbum()).thenReturn("album");
		when(songToAdd.getSongArtistFullName()).thenReturn("artist");
		// Act
		DbQueryStatus status = songDalImpl.addSong(songToAdd);
		// Assert
		verify(mongoTemplate, never()).insert(any(Song.class), anyString());
		assertEquals((String) "POST", (String) status.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_ERROR_GENERIC,
				(DbQueryExecResult) status.getdbQueryExecResult());
		assertNull((Object) status.getData());
	}

	@Test
	@Tag("invalid")
	public void addSong_withNullAlbum_doesNotInsertAndReturnsError() {
		// Arrange
		Song songToAdd = mock(Song.class);
		when(songToAdd.getSongName()).thenReturn("name");
		when(songToAdd.getSongAlbum()).thenReturn(null);
		when(songToAdd.getSongArtistFullName()).thenReturn("artist");
		// Act
		DbQueryStatus status = songDalImpl.addSong(songToAdd);
		// Assert
		verify(mongoTemplate, never()).insert(any(Song.class), anyString());
		assertEquals((String) "POST", (String) status.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_ERROR_GENERIC,
				(DbQueryExecResult) status.getdbQueryExecResult());
		assertNull((Object) status.getData());
	}

	@Test
	@Tag("invalid")
	public void addSong_withNullArtist_doesNotInsertAndReturnsError() {
		// Arrange
		Song songToAdd = mock(Song.class);
		when(songToAdd.getSongName()).thenReturn("name");
		when(songToAdd.getSongAlbum()).thenReturn("album");
		when(songToAdd.getSongArtistFullName()).thenReturn(null);
		// Act
		DbQueryStatus status = songDalImpl.addSong(songToAdd);
		// Assert
		verify(mongoTemplate, never()).insert(any(Song.class), anyString());
		assertEquals((String) "POST", (String) status.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_ERROR_GENERIC,
				(DbQueryExecResult) status.getdbQueryExecResult());
		assertNull((Object) status.getData());
	}

	@Test
	@Tag("boundary")
	public void addSong_validInputButInsertReturnsNull_returnsErrorAndNoData() {
		// Arrange
		Song songToAdd = mock(Song.class);
		when(songToAdd.getSongName()).thenReturn("name");
		when(songToAdd.getSongAlbum()).thenReturn("album");
		when(songToAdd.getSongArtistFullName()).thenReturn("artist");
		when(mongoTemplate.insert(songToAdd, "songs")).thenReturn(null);
		// Act
		DbQueryStatus status = songDalImpl.addSong(songToAdd);
		// Assert
		verify(mongoTemplate, times(1)).insert(songToAdd, "songs");
		assertEquals((String) "POST", (String) status.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_ERROR_GENERIC,
				(DbQueryExecResult) status.getdbQueryExecResult());
		assertNull((Object) status.getData());
	}

	@Test
	@Tag("valid")
	public void addSong_validSong_setsReturnedDataFromInsertedJsonRepresentation() {
		// Arrange
		Song songToAdd = mock(Song.class);
		when(songToAdd.getSongName()).thenReturn("n");
		when(songToAdd.getSongAlbum()).thenReturn("a");
		when(songToAdd.getSongArtistFullName()).thenReturn("ar");
		Song inserted = mock(Song.class);
		Map<String, String> json = new HashMap<>();
		json.put("k", "v");
		when(inserted.getJsonRepresentation()).thenReturn(json);
		when(mongoTemplate.insert(songToAdd, "songs")).thenReturn(inserted);
		// Act
		DbQueryStatus status = songDalImpl.addSong(songToAdd);
		// Assert
		verify(mongoTemplate, times(1)).insert(songToAdd, "songs");
		assertEquals((Object) json, (Object) status.getData());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
		assertEquals((String) "POST", (String) status.getMessage());
	}

}