
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=deleteSongById_1d2081da46
ROOST_METHOD_SIG_HASH=deleteSongById_b3ea802621

Scenario 1: Successful deletion when song exists and delete is acknowledged

Details:
  TestName: deleteWithExistingSongAndAcknowledgedResultReturnsOk
  Description: Verifies that when the provided songId is a valid ObjectId, the song exists in the database, and MongoTemplate.remove returns an acknowledged DeleteResult, the method returns a DbQueryStatus with operation "DELETE" and execution result DbQueryExecResult.QUERY_OK.

Execution:
  Arrange: Set up a valid 24-hex string songId. Mock MongoTemplate.findById to return a non-null Song. Mock MongoTemplate.remove to return a DeleteResult whose wasAcknowledged() is true.
  Act: Invoke deleteSongById with the prepared songId.
  Assert: Use JUnit assertions to confirm the returned DbQueryStatus is not null, its operation is "DELETE", and its execution result equals DbQueryExecResult.QUERY_OK. Verify MongoTemplate.remove was called exactly once with the same Song instance and the collection name "songs".

Validation:
  Confirms the happy-path behavior: when a song is found and deletion is acknowledged by MongoDB, the method correctly switches the status from the default ERR404 to OK. It also validates that the correct collection name ("songs") and entity instance are used.

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import com.mongodb.client.result.DeleteResult;
import org.bson.types.ObjectId;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Repository;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.same;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyZeroInteractions;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class SongDalImplDeleteSongByIdTest {

	@Mock
	private MongoTemplate mongoTemplate;

	private SongDalImpl songDalImpl;

	@Before
	public void setUp() {
		this.songDalImpl = new SongDalImpl(mongoTemplate);
	}

	@Test
	@Category(Categories.valid.class)
	public void testDeleteWithExistingSongAndAcknowledgedResultReturnsOk() {
		String songId = new ObjectId().toHexString();
		Song song = new Song("title", "artist", "album"); // TODO adjust song metadata if
															// domain changes
		when(mongoTemplate.findById(any(ObjectId.class), eq(Song.class))).thenReturn(song);
		when(mongoTemplate.remove(same(song), eq("songs"))).thenReturn(DeleteResult.acknowledged(1L));
		DbQueryStatus status = songDalImpl.deleteSongById(songId);
		assertNotNull((Object) status);
		assertEquals((String) "DELETE", (String) status.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) status.getdbQueryExecResult());
		verify(mongoTemplate, times(1)).remove(same(song), eq("songs"));
	}

	@Test
	@Category(Categories.invalid.class)
	public void testDeleteWhenSongDoesNotExistReturnsNotFound() {
		String songId = new ObjectId().toHexString();
		when(mongoTemplate.findById(any(ObjectId.class), eq(Song.class))).thenReturn(null);
		DbQueryStatus status = songDalImpl.deleteSongById(songId);
		assertNotNull((Object) status);
		assertEquals((String) "DELETE", (String) status.getMessage());
		// Expect not OK since song not found; default remains ERR404
		org.junit.Assert.assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) status.getdbQueryExecResult());
		verify(mongoTemplate, never()).remove(org.mockito.ArgumentMatchers.any(Song.class), eq("songs"));
	}

	@Test
	@Category(Categories.invalid.class)
	public void testDeleteWithInvalidObjectIdReturnsErr() {
		String invalidSongId = "not-a-valid-object-id";
		DbQueryStatus status = songDalImpl.deleteSongById(invalidSongId);
		assertNotNull((Object) status);
		assertEquals((String) "DELETE", (String) status.getMessage());
		org.junit.Assert.assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) status.getdbQueryExecResult());
		verifyZeroInteractions(mongoTemplate);
	}

	@Test
	@Category(Categories.invalid.class)
	public void testDeleteWhenMongoTemplateRemoveThrowsExceptionReturnsErr() {
		String songId = new ObjectId().toHexString();
		Song song = new Song("title-x", "artist-x", "album-x");
		when(mongoTemplate.findById(any(ObjectId.class), eq(Song.class))).thenReturn(song);
		when(mongoTemplate.remove(same(song), eq("songs"))).thenThrow(new RuntimeException("delete failed")); // TODO
																												// adjust
																												// exception
																												// condition
																												// if
																												// needed
		DbQueryStatus status = songDalImpl.deleteSongById(songId);
		assertNotNull((Object) status);
		assertEquals((String) "DELETE", (String) status.getMessage());
		org.junit.Assert.assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) status.getdbQueryExecResult());
	}

	@Test
	@Category(Categories.invalid.class)
	public void testDeleteWhenDeleteResultIsUnacknowledgedReturnsNotFound() {
		String songId = new ObjectId().toHexString();
		Song song = new Song("title-y", "artist-y", "album-y");
		when(mongoTemplate.findById(any(ObjectId.class), eq(Song.class))).thenReturn(song);
		when(mongoTemplate.remove(same(song), eq("songs"))).thenReturn(DeleteResult.unacknowledged());
		DbQueryStatus status = songDalImpl.deleteSongById(songId);
		assertNotNull((Object) status);
		assertEquals((String) "DELETE", (String) status.getMessage());
		org.junit.Assert.assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) status.getdbQueryExecResult());
		verify(mongoTemplate, times(1)).remove(same(song), eq("songs"));
	}

	@Test
	@Category(Categories.boundary.class)
	public void testDeleteWhenDeleteResultIsNullHandledAsErr() {
		String songId = new ObjectId().toHexString();
		Song song = new Song("title-z", "artist-z", "album-z");
		when(mongoTemplate.findById(any(ObjectId.class), eq(Song.class))).thenReturn(song);
		when(mongoTemplate.remove(same(song), eq("songs"))).thenReturn(null);
		DbQueryStatus status = songDalImpl.deleteSongById(songId);
		assertNotNull((Object) status);
		assertEquals((String) "DELETE", (String) status.getMessage());
		org.junit.Assert.assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) status.getdbQueryExecResult());
	}

}