
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSong_7432879ff4
ROOST_METHOD_SIG_HASH=addSong_159672f987


Scenario 1: Successful add when DAL returns OK and external service returns status OK

Details:
  TestName: addSong_whenDalOkAndExternalOk_returnsOkResponse
  Description: Verifies that when SongDal.addSong returns DbQueryExecResult.QUERY_OK and the external service responds with a JSON body containing status = "OK", the method returns a response map representing success. It checks that the "path" is correctly formatted, the original DAL message is preserved, and the data returned by DAL is propagated via Utils.setResponseStatus.

Execution:
  Arrange: Prepare a params map containing entries for Song.KEY_SONG_NAME, Song.KEY_SONG_ARTIST_FULL_NAME, and Song.KEY_SONG_ALBUM. Mock SongDal.addSong to return a DbQueryStatus with DbQueryExecResult.QUERY_OK and a data payload of type Map<String, String>. Mock OkHttpClient to return a Response whose body is a JSON string like {"status":"OK"}. Provide a valid HttpServletRequest such that Utils.getUrl(request) is stable for assertion.
  Act: Invoke SongController.addSong with the prepared params and request.
  Assert: Use JUnit assertions to check that:
    - response contains "path" equal to "POST " + Utils.getUrl(request).
    - response contains "message" equal to the DbQueryStatus message returned by SongDal.
    - response reflects a successful status consistent with DbQueryExecResult.QUERY_OK.
    - response includes the same data object that DAL returned (as propagated by Utils.setResponseStatus).

Validation:
  Confirms the happy-path behavior: DAL success plus external confirmation leads to an overall successful response, correctly formatted path, preserved message, and data propagation.

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import okhttp3.Call;
import okhttp3.MediaType;
import okhttp3.Protocol;
import okhttp3.Request;
import okhttp3.Response;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.when;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.RequestBody;

@RunWith(MockitoJUnitRunner.class)
public class SongControllerAddSongTest {

	@Mock
	private SongDal mockSongDal;

	@Mock
	private okhttp3.OkHttpClient mockHttpClient;

	@Mock
	private Call mockCall;

	@Mock
	private HttpServletRequest mockRequest;

	private SongController controller;

	@Before
	public void setUp() throws Exception {
		controller = new SongController(mockSongDal);
		injectClient(controller, mockHttpClient);
		when(mockRequest.getRequestURL()).thenReturn(new StringBuffer("http://localhost/api/v1/songs"));
	}

	@Test
	@Category(Categories.valid.class)
	public void testAddSong_whenDalOkAndExternalOk_returnsOkResponse() throws Exception {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Song A");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist A");
		params.put(Song.KEY_SONG_ALBUM, "Album A");
		DbQueryStatus dalStatus = new DbQueryStatus("created", DbQueryExecResult.QUERY_OK);
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-id-1");
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		when(mockHttpClient.newCall(any(Request.class))).thenReturn(mockCall);
		Response okResponse = buildJsonResponse(200, "{\"status\":\"OK\"}");
		when(mockCall.execute()).thenReturn(okResponse);
		Map<String, Object> actual = controller.addSong(params, mockRequest);
		String path = (String) actual.get("path");
		assertTrue(path != null && path.startsWith("POST "));
		assertEquals("created", (String) actual.get("message"));
		assertEquals(DbQueryExecResult.QUERY_OK, dalStatus.getdbQueryExecResult());
		assertEquals(dalData, (Map<?, ?>) dalStatus.getData());
	}

	@Test
	@Category(Categories.invalid.class)
	public void testAddSong_whenDalOkAndExternalNotOk_setsNotFound() throws Exception {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Song B");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist B");
		params.put(Song.KEY_SONG_ALBUM, "Album B");
		DbQueryStatus dalStatus = new DbQueryStatus("created", DbQueryExecResult.QUERY_OK);
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-id-2");
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		when(mockHttpClient.newCall(any(Request.class))).thenReturn(mockCall);
		Response notOkResponse = buildJsonResponse(200, "{\"status\":\"NOT_OK\"}");
		when(mockCall.execute()).thenReturn(notOkResponse);
		Map<String, Object> actual = controller.addSong(params, mockRequest);
		String path = (String) actual.get("path");
		assertTrue(path != null && path.startsWith("POST "));
		assertEquals("created", (String) actual.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_NOT_FOUND, dalStatus.getdbQueryExecResult());
		assertEquals(dalData, (Map<?, ?>) dalStatus.getData());
	}

	@Test
	@Category(Categories.invalid.class)
	public void testAddSong_whenDalOkAndExternalThrows_setsGenericError() throws Exception {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Song C");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist C");
		params.put(Song.KEY_SONG_ALBUM, "Album C");
		DbQueryStatus dalStatus = new DbQueryStatus("created", DbQueryExecResult.QUERY_OK);
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-id-3");
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		when(mockHttpClient.newCall(any(Request.class))).thenReturn(mockCall);
		when(mockCall.execute()).thenThrow(new IOException("network down"));
		Map<String, Object> actual = controller.addSong(params, mockRequest);
		String path = (String) actual.get("path");
		assertTrue(path != null && path.startsWith("POST "));
		assertEquals("created", (String) actual.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, dalStatus.getdbQueryExecResult());
		assertEquals(dalData, (Map<?, ?>) dalStatus.getData());
	}

	@Test
	@Category(Categories.boundary.class)
	public void testAddSong_whenDalError_doesNotCallExternal() {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Song D");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist D");
		params.put(Song.KEY_SONG_ALBUM, "Album D");
		DbQueryStatus dalStatus = new DbQueryStatus("error", DbQueryExecResult.QUERY_ERROR_GENERIC);
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-id-4");
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		Map<String, Object> actual = controller.addSong(params, mockRequest);
		Mockito.verify(mockHttpClient, never()).newCall(any(Request.class));
		String path = (String) actual.get("path");
		assertTrue(path != null && path.startsWith("POST "));
		assertEquals("error", (String) actual.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, dalStatus.getdbQueryExecResult());
		assertEquals(dalData, (Map<?, ?>) dalStatus.getData());
	}

	private void injectClient(SongController target, okhttp3.OkHttpClient client) throws Exception {
		Field clientField = SongController.class.getDeclaredField("client");
		clientField.setAccessible(true);
		clientField.set(target, client);
	}

	private Response buildJsonResponse(int code, String json) {
		okhttp3.ResponseBody body = okhttp3.ResponseBody.create(MediaType.parse("application/json; charset=utf-8"),
				json);
		Request req = new Request.Builder().url("http://localhost/test").build();
		return new Response.Builder().code(code)
			.protocol(Protocol.HTTP_1_1)
			.message("OK")
			.request(req)
			.body(body)
			.build();
	}

}