
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=deleteSongById_1d2081da46
ROOST_METHOD_SIG_HASH=deleteSongById_b3ea802621

Scenario 1: Successful deletion when song exists and delete is acknowledged

Details:
  TestName: deleteWithExistingSongAndAcknowledgedResultReturnsOk
  Description: Verifies that when the provided songId is a valid ObjectId, the song exists in the database, and MongoTemplate.remove returns an acknowledged DeleteResult, the method returns a DbQueryStatus with operation "DELETE" and execution result DbQueryExecResult.QUERY_OK.

Execution:
  Arrange: Set up a valid 24-hex string songId. Mock MongoTemplate.findById to return a non-null Song. Mock MongoTemplate.remove to return a DeleteResult whose wasAcknowledged() is true.
  Act: Invoke deleteSongById with the prepared songId.
  Assert: Use JUnit assertions to confirm the returned DbQueryStatus is not null, its operation is "DELETE", and its execution result equals DbQueryExecResult.QUERY_OK. Verify MongoTemplate.remove was called exactly once with the same Song instance and the collection name "songs".

Validation:
  Confirms the happy-path behavior: when a song is found and deletion is acknowledged by MongoDB, the method correctly switches the status from the default ERR404 to OK. It also validates that the correct collection name ("songs") and entity instance are used.

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import com.mongodb.client.result.DeleteResult;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentMatchers;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Repository;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.any;
import static org.mockito.Mockito.anyString;
import static org.mockito.Mockito.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyZeroInteractions;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;

@ExtendWith(MockitoExtension.class)
public class SongDalImplDeleteSongByIdTest {

	@Mock
	private MongoTemplate mongoTemplate;

	private SongDalImpl sut;

	@BeforeEach
	public void setup() {
		this.sut = new SongDalImpl(mongoTemplate);
	}

	@Test
	@Tag("valid")
	public void deleteWithExistingSongAndAcknowledgedResultReturnsOk() {
		String songId = new ObjectId().toHexString();
		ObjectId expectedObjectId = new ObjectId(songId);
		Song existingSong = new Song("t1", "a1", "al1");
		existingSong.setId(expectedObjectId);
		when(mongoTemplate.findById(eq(expectedObjectId), eq(Song.class))).thenReturn(existingSong);
		DeleteResult acknowledged = DeleteResult.acknowledged(1);
		when(mongoTemplate.remove(eq(existingSong), eq("songs"))).thenReturn(acknowledged);
		DbQueryStatus result = sut.deleteSongById(songId);
		assertNotNull((Object) result);
		assertEquals((String) "DELETE", (String) result.getMessage());
		assertEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK, (DbQueryExecResult) result.getdbQueryExecResult());
		assertNull((Object) result.getData());
		verify(mongoTemplate, times(1)).remove(eq(existingSong), eq("songs"));
	}

	@Test
	@Tag("boundary")
	public void deleteWithExistingSongAndUnacknowledgedResultDoesNotReturnOk() {
		String songId = new ObjectId().toHexString();
		ObjectId expectedObjectId = new ObjectId(songId);
		Song existingSong = new Song("t2", "a2", "al2");
		existingSong.setId(expectedObjectId);
		when(mongoTemplate.findById(eq(expectedObjectId), eq(Song.class))).thenReturn(existingSong);
		DeleteResult unacknowledged = DeleteResult.unacknowledged();
		when(mongoTemplate.remove(eq(existingSong), eq("songs"))).thenReturn(unacknowledged);
		DbQueryStatus result = sut.deleteSongById(songId);
		assertNotNull((Object) result);
		assertEquals((String) "DELETE", (String) result.getMessage());
		assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) result.getdbQueryExecResult());
		assertNull((Object) result.getData());
		verify(mongoTemplate, times(1)).remove(eq(existingSong), eq("songs"));
	}

	@Test
	@Tag("invalid")
	public void deleteWhenSongNotFoundReturnsNonOkAndDoesNotCallRemove() {
		String songId = new ObjectId().toHexString();
		ObjectId expectedObjectId = new ObjectId(songId);
		when(mongoTemplate.findById(eq(expectedObjectId), eq(Song.class))).thenReturn(null);
		DbQueryStatus result = sut.deleteSongById(songId);
		assertNotNull((Object) result);
		assertEquals((String) "DELETE", (String) result.getMessage());
		assertNotNull((Object) result.getdbQueryExecResult());
		assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) result.getdbQueryExecResult());
		assertNull((Object) result.getData());
		verify(mongoTemplate, never()).remove(ArgumentMatchers.<Song>any(), anyString());
	}

	@Test
	@Tag("invalid")
	public void deleteWithInvalidObjectIdReturnsErrorAndNoDbCalls() {
		String invalidId = "not-a-valid-objectid"; // TODO replace with another invalid id
													// format if needed
		DbQueryStatus result = sut.deleteSongById(invalidId);
		assertNotNull((Object) result);
		assertEquals((String) "DELETE", (String) result.getMessage());
		assertNotNull((Object) result.getdbQueryExecResult());
		assertNotEquals((DbQueryExecResult) DbQueryExecResult.QUERY_OK,
				(DbQueryExecResult) result.getdbQueryExecResult());
		assertNull((Object) result.getData());
		verifyZeroInteractions(mongoTemplate);
	}

}