
// ********RoostGPT********
/*
Test generated by RoostGPT for test rahul-spotify using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=addSong_7432879ff4
ROOST_METHOD_SIG_HASH=addSong_159672f987


Scenario 1: Successful add when DAL returns OK and external service returns status OK

Details:
  TestName: addSong_whenDalOkAndExternalOk_returnsOkResponse
  Description: Verifies that when SongDal.addSong returns DbQueryExecResult.QUERY_OK and the external service responds with a JSON body containing status = "OK", the method returns a response map representing success. It checks that the "path" is correctly formatted, the original DAL message is preserved, and the data returned by DAL is propagated via Utils.setResponseStatus.

Execution:
  Arrange: Prepare a params map containing entries for Song.KEY_SONG_NAME, Song.KEY_SONG_ARTIST_FULL_NAME, and Song.KEY_SONG_ALBUM. Mock SongDal.addSong to return a DbQueryStatus with DbQueryExecResult.QUERY_OK and a data payload of type Map<String, String>. Mock OkHttpClient to return a Response whose body is a JSON string like {"status":"OK"}. Provide a valid HttpServletRequest such that Utils.getUrl(request) is stable for assertion.
  Act: Invoke SongController.addSong with the prepared params and request.
  Assert: Use JUnit assertions to check that:
    - response contains "path" equal to "POST " + Utils.getUrl(request).
    - response contains "message" equal to the DbQueryStatus message returned by SongDal.
    - response reflects a successful status consistent with DbQueryExecResult.QUERY_OK.
    - response includes the same data object that DAL returned (as propagated by Utils.setResponseStatus).

Validation:
  Confirms the happy-path behavior: DAL success plus external confirmation leads to an overall successful response, correctly formatted path, preserved message, and data propagation.

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import okhttp3.Call;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import org.mockito.Mockito;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import okhttp3.FormBody;
import okhttp3.RequestBody;

public class SongControllerAddSongTest {

	private SongDal mockSongDal;

	private OkHttpClient mockHttpClient;

	private SongController songController;

	@BeforeEach
	public void setUp() throws Exception {
		mockSongDal = Mockito.mock(SongDal.class);
		mockHttpClient = Mockito.mock(OkHttpClient.class);
		songController = new SongController(mockSongDal);
		Field clientField = SongController.class.getDeclaredField("client");
		clientField.setAccessible(true);
		clientField.set(songController, mockHttpClient);
	}

	private void mockExternalResponse(String jsonBody) throws Exception {
		Call mockCall = Mockito.mock(Call.class);
		Response mockResponse = Mockito.mock(Response.class);
		okhttp3.ResponseBody mockResponseBody = Mockito.mock(okhttp3.ResponseBody.class);
		when(mockHttpClient.newCall(any(Request.class))).thenReturn(mockCall);
		when(mockCall.execute()).thenReturn(mockResponse);
		when(mockResponse.body()).thenReturn(mockResponseBody);
		when(mockResponseBody.string()).thenReturn(jsonBody);
	}

	private HttpServletRequest createMockRequest() {
		HttpServletRequest request = Mockito.mock(HttpServletRequest.class);
		when(request.getRequestURL()).thenReturn(new StringBuffer("http://localhost/api/songs"));
		when(request.getRequestURI()).thenReturn("/api/songs");
		when(request.getScheme()).thenReturn("http");
		when(request.getServerName()).thenReturn("localhost");
		when(request.getServerPort()).thenReturn(80);
		when(request.getContextPath()).thenReturn("");
		when(request.getServletPath()).thenReturn("/api/songs");
		when(request.getPathInfo()).thenReturn(null);
		when(request.getQueryString()).thenReturn(null);
		when(request.getMethod()).thenReturn("POST");
		return request;
	}

	@Test
	@Tag("integration")
	public void testAddSong_whenDalOkAndExternalOk_returnsOkResponse() throws Exception {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Track A");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist A");
		params.put(Song.KEY_SONG_ALBUM, "Album A");
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-123");
		String dalMessage = "Song added successfully";
		DbQueryStatus dalStatus = new DbQueryStatus(dalMessage, DbQueryExecResult.QUERY_OK);
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		mockExternalResponse("{\"status\":\"OK\"}");
		HttpServletRequest request = createMockRequest();
		Map<String, Object> response = songController.addSong(params, request);
		assertNotNull((String) response.get("path"));
		assertTrue(((String) response.get("path")).startsWith("POST "));
		assertEquals(dalMessage, (String) response.get("message"));
		assertEquals(DbQueryExecResult.QUERY_OK, (DbQueryExecResult) response.get("status"));
		@SuppressWarnings("unchecked")
		Map<String, String> data = (Map<String, String>) response.get("data");
		assertSame(dalData, data);
		verify(mockSongDal, times(1)).addSong(any(Song.class));
		verify(mockHttpClient, times(1)).newCall(any(Request.class));
	}

	@Test
	@Tag("invalid")
	public void testAddSong_whenDalOkAndExternalReturnsNonOk_setsNotFoundStatus() throws Exception {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Track B");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist B");
		params.put(Song.KEY_SONG_ALBUM, "Album B");
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-456");
		String dalMessage = "Song added with warning";
		DbQueryStatus dalStatus = new DbQueryStatus(dalMessage, DbQueryExecResult.QUERY_OK);
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		mockExternalResponse("{\"status\":\"NOK\"}");
		HttpServletRequest request = createMockRequest();
		Map<String, Object> response = songController.addSong(params, request);
		assertNotNull((String) response.get("path"));
		assertTrue(((String) response.get("path")).startsWith("POST "));
		assertEquals(dalMessage, (String) response.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_NOT_FOUND, (DbQueryExecResult) response.get("status"));
		@SuppressWarnings("unchecked")
		Map<String, String> data = (Map<String, String>) response.get("data");
		assertSame(dalData, data);
		verify(mockSongDal, times(1)).addSong(any(Song.class));
		verify(mockHttpClient, times(1)).newCall(any(Request.class));
	}

	@Test
	@Tag("invalid")
	public void testAddSong_whenDalOkAndExternalThrows_setsGenericErrorStatus() throws Exception {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Track C");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist C");
		params.put(Song.KEY_SONG_ALBUM, "Album C");
		Map<String, String> dalData = new HashMap<>();
		dalData.put("id", "song-789");
		String dalMessage = "Song added but external failed";
		DbQueryStatus dalStatus = new DbQueryStatus(dalMessage, DbQueryExecResult.QUERY_OK);
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		Call mockCall = Mockito.mock(Call.class);
		when(mockHttpClient.newCall(any(Request.class))).thenReturn(mockCall);
		when(mockCall.execute()).thenThrow(new RuntimeException("Simulated IO error"));
		HttpServletRequest request = createMockRequest();
		Map<String, Object> response = songController.addSong(params, request);
		assertNotNull((String) response.get("path"));
		assertTrue(((String) response.get("path")).startsWith("POST "));
		assertEquals(dalMessage, (String) response.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, (DbQueryExecResult) response.get("status"));
		@SuppressWarnings("unchecked")
		Map<String, String> data = (Map<String, String>) response.get("data");
		assertSame(dalData, data);
		verify(mockSongDal, times(1)).addSong(any(Song.class));
		verify(mockHttpClient, times(1)).newCall(any(Request.class));
	}

	@Test
	@Tag("invalid")
	public void testAddSong_whenDalNotOk_doesNotCallExternal_andReturnsDalStatus() {
		Map<String, String> params = new HashMap<>();
		params.put(Song.KEY_SONG_NAME, "Track D");
		params.put(Song.KEY_SONG_ARTIST_FULL_NAME, "Artist D");
		params.put(Song.KEY_SONG_ALBUM, "Album D");
		Map<String, String> dalData = new HashMap<>();
		dalData.put("error", "validation");
		String dalMessage = "Validation failed";
		DbQueryStatus dalStatus = new DbQueryStatus(dalMessage, DbQueryExecResult.QUERY_ERROR_GENERIC);
		dalStatus.setData(dalData);
		when(mockSongDal.addSong(any(Song.class))).thenReturn(dalStatus);
		HttpServletRequest request = createMockRequest();
		Map<String, Object> response = songController.addSong(params, request);
		assertNotNull((String) response.get("path"));
		assertTrue(((String) response.get("path")).startsWith("POST "));
		assertEquals(dalMessage, (String) response.get("message"));
		assertEquals(DbQueryExecResult.QUERY_ERROR_GENERIC, (DbQueryExecResult) response.get("status"));
		@SuppressWarnings("unchecked")
		Map<String, String> data = (Map<String, String>) response.get("data");
		assertSame(dalData, data);
		verify(mockSongDal, times(1)).addSong(any(Song.class));
		verify(mockHttpClient, never()).newCall(any(Request.class));
	}

}