
// ********RoostGPT********
/*
Test generated by RoostGPT for test oct-24-java-unit-spotify using AI Type AWS Bedrock Runtime AI and AI Model us.anthropic.claude-3-sonnet-20240229-v1:0

ROOST_METHOD_HASH=deleteSongById_1d2081da46
ROOST_METHOD_SIG_HASH=deleteSongById_b3ea802621

Scenario 1: Test for successful deletion of a song by ID

Details:
  TestName: deleteSongByValidId
  Description: This test verifies that the deleteSongById method correctly deletes a song from the database when a valid song ID is provided.

Execution:
  Arrange:
    - Create a sample Song object.
    - Insert the sample Song object into the database using the addSong method.
    - Retrieve the ID of the inserted Song object.
  Act: Invoke the deleteSongById method with the retrieved Song ID.
  Assert: Verify that the returned DbQueryStatus has a DbQueryExecResult of OK.

Validation:
  The assertion ensures that the deleteSongById method successfully removed the song from the database when a valid ID was provided. This test covers the happy path scenario and verifies the correct behavior of the method under normal conditions.

Scenario 2: Test for deletion of a non-existent song by ID

Details:
  TestName: deleteSongByInvalidId
  Description: This test verifies that the deleteSongById method handles the case when an invalid or non-existent song ID is provided.

Execution:
  Arrange: Generate a random or invalid ObjectId that does not correspond to any existing song in the database.
  Act: Invoke the deleteSongById method with the invalid ObjectId.
  Assert: Verify that the returned DbQueryStatus has a DbQueryExecResult of ERR404 (QUERY_ERROR_NOT_FOUND).

Validation:
  The assertion ensures that the deleteSongById method correctly handles the case when the provided song ID does not exist in the database. This test covers an edge case and verifies the correct error handling and reporting of the method.

Scenario 3: Test for handling exceptions during deletion

Details:
  TestName: deleteSongByInvalidInput
  Description: This test verifies that the deleteSongById method handles exceptions properly when an invalid input is provided.

Execution:
  Arrange: Prepare a test case with an invalid input, such as a null or malformed string for the songId parameter.
  Act: Invoke the deleteSongById method with the invalid input.
  Assert: Verify that the returned DbQueryStatus has a DbQueryExecResult of ERR (QUERY_ERROR_GENERIC).

Validation:
  The assertion ensures that the deleteSongById method correctly handles and reports exceptions that may occur due to invalid input or other unexpected scenarios. This test covers error handling and verifies the method's robustness against various types of invalid inputs.

*/

// ********RoostGPT********
package com.csc301.songmicroservice;

import com.mongodb.client.result.DeleteResult;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.stereotype.Repository;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@SpringBootTest
class SongDalImplDeleteSongByIdTest {

	@Autowired
	private MongoTemplate mongoTemplate;

	private SongDalImpl songDalImpl;

	@BeforeEach
	void setUp() {
		songDalImpl = new SongDalImpl(mongoTemplate);
	}

	@Test
	@Tag("valid")
	void deleteSongByValidId() {
		// Arrange
		Song song = new Song("Test Song", "Test Artist", "Test Album");
		DbQueryStatus addStatus = songDalImpl.addSong(song);
		String songId = addStatus.getData().toString().split("=")[1];
		// Act
		DbQueryStatus deleteStatus = songDalImpl.deleteSongById(songId);
		// Assert
		assertEquals(DbQueryExecResult.QUERY_OK, deleteStatus.getdbQueryExecResult());
	}

	@ParameterizedTest
	@ValueSource(strings = { "invalidId", "null" })
	@Tag("invalid")
	void deleteSongByInvalidId(String invalidId) {
		// Act
		DbQueryStatus deleteStatus = songDalImpl.deleteSongById(invalidId);
		// Assert
		assertEquals(DbQueryExecResult.QUERY_ERROR_NOT_FOUND, deleteStatus.getdbQueryExecResult());
	}

	@Test
	@Tag("boundary")
	void deleteSongByNonExistentId() {
		// Arrange
		ObjectId nonExistentId = new ObjectId();
		// Act
		DbQueryStatus deleteStatus = songDalImpl.deleteSongById(nonExistentId.toString());
		// Assert
		assertEquals(DbQueryExecResult.QUERY_ERROR_NOT_FOUND, deleteStatus.getdbQueryExecResult());
	}

	@Test
	@Tag("integration")
	void deleteSongByIdWithMockedMongoTemplate() {
		// Arrange
		MongoTemplate mockMongoTemplate = mock(MongoTemplate.class);
		songDalImpl = new SongDalImpl(mockMongoTemplate);
		ObjectId validId = new ObjectId();
		Song song = new Song("Test Song", "Test Artist", "Test Album");
		when(mockMongoTemplate.findById(validId, Song.class)).thenReturn(song);
		DeleteResult mockDeleteResult = mock(DeleteResult.class);
		when(mockDeleteResult.wasAcknowledged()).thenReturn(true);
		when(mockMongoTemplate.remove(song, "songs")).thenReturn(mockDeleteResult);
		// Act
		DbQueryStatus deleteStatus = songDalImpl.deleteSongById(validId.toString());
		// Assert
		assertEquals(DbQueryExecResult.QUERY_OK, deleteStatus.getdbQueryExecResult());
		verify(mockMongoTemplate, times(1)).findById(validId, Song.class);
		verify(mockMongoTemplate, times(1)).remove(song, "songs");
	}

}